### ISSUE TITLE
verbose_name_plural დაუმატე

### ISSUE THREAD

**Issue by MariamKipshidze** [Lasha-Nikolaishvili/tbc-django-project#1]
https://github.com/Lasha-Nikolaishvili/tbc-django-project/blob/8c96eb3b37174413748a4a6c63bf1e3b5552c5af/market/models.py#L38

**Comment by Lasha-Nikolaishvili** [comment]
ვიფიქრე მაგაზე, მაგრამ დოკუმენტაციაში ეწერა, რომ default-ად მრავლობითში verbose_name-ს (s)-ს უმატებს თავისით და რანდგან book-ის შემთხვევაში გრამატიკულად სწორად გამოდიოდა books აღარ დავამატე. მაინც საჭიროა კონვენციით?

**Comment by MariamKipshidze** [comment]
და verbose_name ზეც იგივე ლოგიკა არ მოქმედებს? ანუ დეფაულტად არ აიღებდა მოდელის სახელს?

**Comment by Lasha-Nikolaishvili** [comment]
კარგი, ანუ კონვენციაა.
