### ISSUE TITLE
ლისტში რატომ გადაგყავს მონაცემები?

### ISSUE THREAD

**Issue by MariamKipshidze** [Lasha-Nikolaishvili/tbc-django-project#3]
https://github.com/Lasha-Nikolaishvili/tbc-django-project/blob/8c96eb3b37174413748a4a6c63bf1e3b5552c5af/market/views.py#L11

**Comment by Lasha-Nikolaishvili** [comment]
ლექციაზე ცოტნემ მსგავსად გვაჩვენა როგორ ბრუნდებოდა ობიექტების სია. უკეთესი გზაც არსებობს?

**Comment by MariamKipshidze** [comment]
book.objects.all() არის ბაზიდან მონაცემების მოთხოვნის კოდი, რაც ოპტიმალური და სწარფია მაგრამ რატომ გადაგყავს ეს ქვერისეტი ლისტში? ზოგადად ქვერისტეტბზე ციკლის გამოყენება არის ყველაზე არაოფტიმალური და ვერიდებით მაქსიმალურად თუ გამოუვალი მდგომარეობა არაა
