### ISSUE TITLE
https://docs.djangoproject.com/en/5.0/topics/i18n/translation/

### ISSUE THREAD

**Issue by MariamKipshidze** [Lasha-Nikolaishvili/tbc-django-project#8]
https://github.com/Lasha-Nikolaishvili/tbc-django-project/blob/3ca41d65970a29371f898d28baa144eece1f94c1/market/models.py#L6

from django.utils.translation import gettext_lazy as _

first_name = models.CharField(verbose_name=_('first name'), max_length=100)

**Comment by Lasha-Nikolaishvili** [comment]
ჩავამატე ესენი
